plugins:
  dashboard:
    class: DashboardPlugin\DashboardPlugin

assets:
  dashboard:
    - src: vendor/bornholm/karambol-plugin-dashboard/public/js
      dest: public/plugins/dashboard/js
    - src: vendor/bornholm/karambol-plugin-dashboard/public/css
      dest: public/plugins/dashboard/css
    - src: vendor/moment/moment
      dest: public/vendor/moment
